version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - kafka-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - kafka-net
    links:
      - zookeeper
    ports:
      - 9092:9092
    #command: docker-compose exec kafka kafka-topics --create --topic registered-customers --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  # micro-service_1:
    # image: projectnamewebapiservice1
    # networks: :
      # - kafka-net
    # links:
      # - kafka
    
networks: 
  kafka-net:
    driver: bridge